import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ColdWater' at '17-5-9 下午4:00' with Gradle 2.11
 *
 * @author ColdWater, @date 17-5-9 下午4:00
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
    }
}
